### ISSUE TITLE
dlpack_unsupported_dtype_refusal: `call_ok_f32` aborts (SIGABRT) on macOS and Windows — main red on 3 of 4 lanes since 2026-08-08

### ISSUE THREAD

**Issue by bwiemz** [bwiemz/NSL#693]
## Summary

`-p nsl-runtime --test dlpack_unsupported_dtype_refusal` fails on **macos-latest, macos-14 and windows-latest**, and passes on **ubuntu-latest**. It reproduces on `main` itself, so every open PR inherits it.

`main` has not had a fully green CI run since **2026-08-08** (run #1203). HEAD is now run #1687 — roughly 480 runs.

On main's latest run [34379792562](https://github.com/bwiemz/NSL/actions/runs/34379792562) (`9410c228`):

| Lane | Result |
|---|---|
| ubuntu-latest | success — unit tests, gated targets, both clippy passes, E2E, ZeRO parity |
| windows-latest | **failure** — Unit tests |
| macos-latest | **failure** — Unit tests |
| macos-14 | **failure** — Unit tests |

## The failure

Captured on macos-latest via the isolated diagnostic step added in #692:

```
running 4 tests
test desc_to_tensor_refuses_an_out_of_range_dtype_tag_instead_of_aborting ... ok
test well_formed_f32_dlpack_imports_and_int64_does_not ... ok
test dlpack_and_export_wrappers_refuse_unsupported_dtypes_without_killing_the_host ... FAILED

---- dlpack_and_export_wrappers_refuse_unsupported_dtypes_without_killing_the_host stdout ----

panicked at crates/nsl-runtime/tests/dlpack_unsupported_dtype_refusal.rs:998:9:
scenario 'call_ok_f32': child exited ExitStatus(unix_wait_status(6)). A refusal must
RETURN, not kill the process — a non-zero status here (139 = SIGSEGV, 134 = SIGABRT)
is the exact regression this gate exists for.
--- stdout ---
running 1 test
test zz_dlpack_refusal_child ...
--- stderr ---
panicked at crates/nsl-runtime/src/c_api/mod.rs:1596:25:

thread panicked while processing panic. aborting.

test result: FAILED. 2 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

Three things are worth pulling out:

1. **The failing scenario is `call_ok_f32` — the well-formed case.** It is the suite's anti-vacuity anchor: a valid f32 tensor driven through the compiled `@export` wrapper via `nsl_model_call`, which must simply succeed. This is not a refusal path misbehaving; it is the happy path aborting.

2. **`c_api/mod.rs:1596:25` is the raw-pointer deref in `nsl_desc_to_tensor`:**
   ```rust
   pub extern "C" fn nsl_desc_to_tensor(desc_ptr: i64) -> i64 {
       if desc_ptr == 0 { return 0; }
       let desc = unsafe { &*(desc_ptr as *const NslTensorDesc) };  // 1596:25
       desc_to_nsl_tensor(desc)
   }
   ```
   Column 25 is the `&*` itself. The null guard passes, so `desc_ptr` is non-zero but not a valid `NslTensorDesc*`.

3. **The panic message is empty, and it double-panics** (`thread panicked while processing panic. aborting.`), which is what turns it into SIGABRT — wait status 6 — rather than a catchable failure. A panic inside a `pub extern "C"` fn cannot unwind, so this takes the child down.

## What has been ruled out

- **Not disk.** This was the leading hypothesis, because `ci.yml`'s `Free runner disk space` step is `if: runner.os == 'Linux'` and its comment describes it as headroom for the ~128 MB binaries these fixtures link into TMPDIR — i.e. the only lane with headroom is the only lane that passes. The diagnostic step prints free space before running anything, and on the failing macOS runner:
  ```
  === free space on the workspace volume ===
  /dev/disk2s5   320Gi   209Gi    91Gi    70%
  === free space on TMPDIR (/var/folders/.../T/) ===
  /dev/disk2s5   320Gi   209Gi    91Gi    70%
  ```
  **91 GiB free.** The disk explanation is dead.

- **Not the other program-linking fixtures.** On the same macOS runner, in the same step: `ccr_periodic_stride_gate` 5 passed / 0 failed, `awq_full_pipeline` **7 passed / 0 failed**. Both link programs successfully there, which also independently clears the linker.

- **Not a recent regression.** The test file's last functional change predates the red by a long way; the last green main run was 2026-08-08.

## Hypothesis (not yet confirmed)

The suite's own module documentation explains why the exe-side and library-side copies of the runtime are expected to stay separate:

> This test binary links `nsl-runtime` as an rlib; `libm.so` (built by `nsl build --shared-lib`) STATICALLY links its own copy. `nm -D` on the test binary shows zero `nsl_*` dynamic symbols, so nothing interposes: they have separate `LAST_ERROR` thread-locals.

That argument is **ELF/Linux-specific** — `nm -D`, `.so`, and ELF's flat global symbol namespace. macOS (Mach-O, two-level namespace) and Windows (PE) resolve symbols differently, so "nothing interposes" is not established on those platforms. If the emitted `@export` wrapper inside `libm.dylib` / `m.dll` binds `nsl_desc_to_tensor` (or the descriptor it is handed) across the exe/library boundary differently than on Linux, the wrapper could pass a pointer that is valid in one image and not the other — which matches a non-null, non-dereferenceable `desc_ptr` exactly.

There is prior art for this class of bug in the history: commit `a441010f` ("review: interposition fixed in codegen, ownership-root guard, …").

This needs someone who can run a macOS or Windows box to confirm; it is stated here as the leading hypothesis, not a conclusion.

## Suggested next steps

1. Reproduce on macOS with `NSL_KEEP_TEMP=1` and inspect the emitted `libm.dylib` (`nm -m`, `otool -L`) for `nsl_*` symbol visibility versus the test binary.
2. Print `desc_ptr` at the top of `nsl_desc_to_tensor` in the child to see whether it is a plausible address, a small constant (e.g. `0x8`, the `Vec::as_mut_ptr()`-of-empty case the suite already documents as scenario 4), or garbage.
3. Give the deref a real guard rather than relying on the `== 0` check, so a bad descriptor becomes a returned refusal instead of an abort — the behaviour this gate exists to enforce.

## Impact

Three of four `build-and-test` lanes are red on every branch and on `main`, and because the unit-test step fails, every step after it — the test-helpers-gated targets, both clippy passes, E2E smoke, and the ZeRO SPMD parity gate — is **skipped** on those three platforms. macOS and Windows have effectively had no clippy or E2E coverage for a month.

**Comment by bwiemz** [comment]
## Windows looks like a *different* defect from macOS — MSVC objects linked by MinGW `ld`

#692's `build-and-test (windows-latest)` lane ([run 34396296707, job 102616742811](https://github.com/bwiemz/NSL/actions/runs/34396296707/job/102616742811)) ran the same diagnostic step. It does **not** show the macOS signature. It shows a hard link failure:

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/15.2.0/.../ld.exe:
  D:\a\NSL\NSL\target\debug\deps\nsl_runtime-3b2e4067815a094f.lib(
    D:/a/NSL/NSL/target/debug/build/onig_sys-53b2ae17ce472796/out/...-regcomp.o
  ):(.text$mn+0xcac1): undefined reference to `__security_check_cookie'
  ... undefined reference to `__security_cookie'
  ... undefined reference to `__GSHandlerCheck'
  ... undefined reference to `sprintf_s'
  ... undefined reference to `_vsnprintf_s'
  ... undefined reference to `__chkstk'
  ... undefined reference to `__report_rangecheckfailure'
collect2.exe: error: ld returned 1 exit status
```

`__security_cookie`, `__security_check_cookie`, `__GSHandlerCheck`, `__report_rangecheckfailure`, `sprintf_s`, `_vsnprintf_s` and `__chkstk` are **MSVC CRT** symbols. They are unresolved because the link is being performed by **MinGW's `ld.exe`** (`C:/mingw64/...`), which does not supply them.

The objects in question are `onig_sys` C objects vendored inside `nsl_runtime-*.lib`. `onig_sys` arrives via `tokenizers`, which is an `interop` dependency — so it is on the path exactly when `interop` is enabled, which is exactly when this test target exists.

So the shape on Windows is: MSVC-compiled objects (windows-latest Rust defaults to `x86_64-pc-windows-msvc`) being linked by a MinGW toolchain. That is a toolchain mismatch in whatever performs the shared-library link, not the non-dereferenceable `desc_ptr` seen on macOS.

**This may warrant splitting into its own issue.** Two platforms, two distinct mechanisms, one symptom (`dlpack_unsupported_dtype_refusal` red). Filing it here for now so the evidence stays together.

### Also from the same Windows run: the other two fixtures pass in isolation

| Fixture | Windows, run alone |
|---|---|
| `awq_full_pipeline` | **ok — 7 passed; 0 failed** (7.04s) |
| `ccr_periodic_stride_gate` | ok |

`awq_full_pipeline` passing alone on Windows is worth recording explicitly: it is red on Windows under `cargo test --workspace` (see #686), and green on Windows when run by itself. Same commit, same platform, same fixture. That points at cross-target interference or contention under the full workspace run rather than a defect in the AWQ path — consistent with it also passing on macOS (7/0) and locally on Linux (7/0).

### Caveat

I have **not** confirmed that this link failure is what makes `dlpack_unsupported_dtype_refusal` fail on Windows. What is confirmed is that the failure occurs, that it is an MSVC/MinGW symbol mismatch, and that it is a different signature from the macOS abort. If `nsl build --shared-lib` is the link that fails, the test's `build_lib` would trip its own
```rust
assert!(out.status.success(), "nsl build --shared-lib failed: {stderr}")
```
rather than reaching the `call_ok_f32` scenario at all — a different failure path from the one this issue documents for macOS. Confirming that needs the Windows `### -p nsl-runtime --features interop --test dlpack_unsupported_dtype_refusal` section of that job log, which sits behind several hundred lines of linker output that the job-log API's tail window cannot reach from here.

---
_Generated by [Claude Code](https://claude.ai/code)_
